/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootSpaRouteImport } from './routes/__root.spa'
import { Route as IndexRouteImport } from './routes/index'

const _rootSpaRoute = _rootSpaRouteImport.update({
  id: '/__root/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spa': typeof _rootSpaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spa': typeof _rootSpaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__root/spa': typeof _rootSpaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spa'
  id: '__root__' | '/' | '/__root/spa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _rootSpaRoute: typeof _rootSpaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/spa': {
      id: '/__root/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof _rootSpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _rootSpaRoute: _rootSpaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
